name: Unit Tests

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Setup Gradle 
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew 
      
      - name: Build and tests
        run: ./gradlew build 
  revert-change:
    runs-on: ubuntu-20.04
    needs: [ build ]  
    if: ${{ failure() }}      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # check out the current and prior state
      - name: "Revert the commit that triggered this run, then push it to main"
        shell: bash
        run: |
          echo "Reverting ${{ github.sha }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert --no-edit ${{ github.sha }}
          git push origin main